### ISSUE TITLE
GitHub Actions doesn’t automatically know where the binary was installed unless it's added to the system PATH

### ISSUE THREAD

**Issue by benmthomas** [tofuutils/tenv-github-action#10]
When using tofuutils/tenv-github-action to install a tool (e.g. Terragrunt), the action reports successful installation but the binary isn’t on the runner’s PATH, so subsequent steps fail with:
```bash
terragrunt: command not found
```

**To Reproduce**
```yaml
- name: Install Terragrunt
  uses: tofuutils/tenv-github-action@main
  with:
    tool_name: tg
    tool_version: 0.67.15
    github_token: ${{ secrets.GITHUB_TOKEN }}

- name: Run terragrunt
  run: terragrunt --version
```
Logs show “Installation of Terragrunt 0.67.15 successful” but then:
```bash
/home/runner/.../script.sh: line 10: terragrunt: command not found
```

**Expected behaviour:**
After installation, the tool’s binary directory (e.g. `$GITHUB_WORKSPACE/.tenv/Terragrunt/0.67.15/`) should be appended to the runner’s `PATH`, so that `terragrunt` (or whatever `<tool_name>` is) is immediately available.

**Actual behavior:**
The action does not modify the runner’s PATH. We must manually add the below step:
```yaml
- run: echo "$GITHUB_WORKSPACE/.tenv/Terragrunt/0.67.15" >> $GITHUB_PATH
```
